version: '3.8'

services:
  mapsmessaging:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - maps-data:/app/data
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped

volumes:
  maps-data: 